### ISSUE TITLE
Firmware for product id 1103 lacks board.bin

### ISSUE THREAD

**Issue by APokorny** [kvalo/ath11k-firmware#9]
I just tried the firmware here:
https://github.com/kvalo/ath11k-firmware/tree/master/WCN6855/hw2.0/1.1/WLAN.HSP.1.1-02431-QCAHSPSWPL_V1_V2_SILICONZ_LITE-1 

with a 5.15.0 kernel on a Elitebook G8 835 with a Qualcomm QCNFA765 . On startup it complains about either a missing board.bin or board-2.bin. In the end I found a firmware binary in chrome os:
https://chromium.googlesource.com/chromiumos/third_party/linux-firmware/+/refs/heads/master/ath11k/WCN6855/hw2.0

I wonder what the original source of those binaries is.

**Comment by MikeSpeigle** [comment]
Thank you for this as of 12/09/2021 the board file in this repo was pushed a few times the last few days have have not worked for me. The one you have linked to worked for me and is working perfect. I have a sparklan wcn6856 m.2 card. Using the amss.bin and m3.bin files you linked or the ones from 02338 or 02431 work for me using the ath11k drivers from kernel 5.15.

**Comment by APokorny** [comment]
It seems that the notebook uses a version of the chip with id=0xff. So there are issues when selecting the right firmware binary:
Further details are in this commit message: https://chromium.googlesource.com/chromiumos/third_party/linux-firmware/+/7b6f472d6b5d24d3b9e6007e009cd801f466c000

**Comment by MikeSpeigle** [comment]
Yes this appears to be the case with the sparklan wcn6856 as well. So far even with the board files updated in this repo since that Dec 29th 2021 Chromium update that you posted still have not worked , But the board.bin file referenced works. So far for me the only two amss.bin and m3.bin files that work are the 1720 and 2431 firmware files. I am not sure what these two files do but with the 2431 files things to be very stable with the exception of 160mhz width which fails to recover after suspend. But I would like to thank you again for bringing attention to this as without your original post I am not sure I would have been able to find on my own that working board file. Here is my chip. 

ath11k_pci 0000:02:00.0: chip_id 0x2 chip_family 0xb board_id 0xff soc_id 0x400c0200
ath11k_pci 0000:02:00.0: fw_version 0x110d897f fw_build_timestamp 2021-05-27 19:36 fw_build_id QC_IMAGE_VERSION_STRING=WLAN.HSP.1.1-02431-QCAHSPSWPL_V1_V2_SILICONZ_LITE-1
